users:
  - user: dw
    pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC3ZCeEfuLThVmUHaqe5TRyGnlnAxj/lXLL3QlibfBxK dw
    sudo: true
  - user: ducnc
    pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFdCWEc2G9r+6g8VosYR+aTkMpjLWMBPTrca75s3eWBa ducnc
    sudo: true
  - user: datbavip10
    pubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdii3VtVFE2pa+6jHlrXtZu+I68MwQSF8TN5Rvim0xJ83j2ER59Xn61Eb7IM2lLrwDH9h7mPtfJePuK2xrmXwjeCZR19iCa2r5Gr/kl4WBmpg4kL6gP85Px2fQ8qAbZ4G3sBQHqeygxpu6qTslcRczxt4eN9QiN8/MBQKspa/WdihOeq2ziMYN8oQKkuUbqV/cLJcNzPzOjpyHzPjrf5GoyhfKTBFaA40Mu5y02cT7e0OTvq7XedKSf5EVFZbjAUbby7msHDIfHD8e24B15ebpPRW0zaycA51FG+1Z1pvKy4hUzr1vFLNWI8pz1Fnv80vyUVU4hTxkXu/2d4bYfCI9 datbavip10
    sudo: true