networks:
  nginx-network:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-vts:1.26
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
    networks:
      - nginx-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - "--nginx.scrape-uri=http://nginx/stub"
    networks:
      - nginx-network
