services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL_FILE: /run/secrets/mongo_root_url
      ME_CONFIG_BASICAUTH: "false"
    secrets:
      - mongo_root_url
    ports:
      - "8081:8081"

secrets:
  mongo_root_url:
    file: /var/secret/docker/mongo_root_url
