services:  
  frontend:
    image: vada898989.azurecr.io/prod-webapp:prod-9eb9a97c
    container_name: frontend
    ports:
      - "3000:80"

  crm:
    image: vada898989.azurecr.io/crm-api:6fdb374b
    container_name: crm
    ports:
      - "8080:8080"
    env_file:
      - /var/secret/docker/crm/app.env
    environment:
      - APP_ENV=development
      - SERVER_ADDRESS=:8080
      - CONTEXT_TIMEOUT=2
      - MONGODB_DATABASE_NAME=vada_prod
      - ACCESS_TOKEN_EXPIRY_HOUR=48
      - REFRESH_TOKEN_EXPIRY_HOUR=168
      - MAILGUN_DOMAIN=mg.vadata.vn
      - VADA_BACKEND_URL=http://qe-app.internal.vadata.vn/
      - VADA_FRONTEND_URL=https://app.vadata.vn
      - VADA_ACL_URL=http://acl-app.internal.vadata.vn
      - ENABLE_SERVICE_PACKAGE=false

  qe:
    image: vada898989.azurecr.io/vada-query-engine:58d9e832
    container_name: qe
    ports:
      - "9675:9675"
    env_file:
      - /var/secret/docker/qe/app.env

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    env_file:
      - /var/secret/docker/es/kibana.env
    environment:
      - ELASTICSEARCH_HOSTS=http://es-app.internal.vadata.vn
    ports:
      - "5601:5601"