services:
  ihn_data_sync:
    build:
      context: .
      dockerfile: Dockerfile
    image: ihn_data_sync:latest
    container_name: ihn_data_sync
    environment:
      MYSQL_USERNAME: "test"
      MYSQL_PASSWORD: "test#2024"
      MYSQL_HOSTNAME: "mysql00.internal.vadata.vn"
      MYSQL_PORT: "3306"
      TARGET_ENDPOINT: "https://services.vadata.vn/ihn/capture"
      SCAN_INTERVAL: 1
