apiVersion: batch/v1
kind: CronJob
metadata:
  name: ihn-data-sync-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ihn-data-sync
            image: vada898989.azurecr.io/ihn_data_sync:latest
            env:
            - name: MYSQL_USERNAME
              value: "test"
            - name: MYSQL_PASSWORD
              value: "test#2024"
            - name: MYSQL_HOSTNAME
              value: "mysql00.internal.vadata.vn"
            - name: MYSQL_PORT
              value: "3306"
            - name: TARGET_ENDPOINT
              value: "https://services.vadata.vn/ihn/capture"
            - name: SCAN_INTERVAL
              value: "15"
          restartPolicy: OnFailure

