FROM python
WORKDIR /app
RUN pip install --no-cache-dir asyncio uvicorn fastapi aiohttp confluent_kafka
COPY *.py .
EXPOSE 8002
CMD ["uvicorn", "es_inserter:app", "--host", "0.0.0.0", "--port", "8002"]