services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=45GB'
    ports:
      - 9090:9090
    volumes:
      - ./prom:/etc/prometheus
      - /var/lib/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=011090
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./gr/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - /var/lib/grafana/data:/var/lib/grafana

  cloudprober:
    image: cloudprober/cloudprober:latest
    container_name: cloudprober
    restart: unless-stopped
    ports:
      - "9313:9313"
    volumes:
      - ./cloudprober:/etc/cloudprober
    command: [ "--config_file", "/etc/cloudprober/cloudprober.conf" ]