secrets:
  es_elastic:
    file: /var/secret/docker/es/elastic

networks:
  etl-network:
    driver: bridge

services:
  es_inserter:
    image: es-inserter:latest
    container_name: es_inserter
    restart: always
    environment:
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic
      ELASTIC_USER: "elastic"
      ELASTIC_URL: "http://demo.internal.vadata.vn:9200"
    secrets:
      - es_elastic
    ports:
      - "8002:8002"
    networks:
      - etl-network
