networks:
  nginx-network:
    driver: bridge

services:
  nginx:
    image: nginx-jwt:1.27.4
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - auth
      - jwt.vtad
      - jwt.dev
      - jwt.app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/letsencrypt:/etc/nginx/ssl
    networks:
      - nginx-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - "--nginx.scrape-uri=http://nginx/stub"
    networks:
      - nginx-network

secrets:
  auth:
    file: /var/secret/nginx/auth
  jwt.vtad:
    file: /var/secret/nginx/jwt.vtad
  jwt.dev:
    file: /var/secret/nginx/jwt.dev
  jwt.app:
    file: /var/secret/nginx/jwt.app
