secrets:
  mysql_crawler:
    file: /var/secret/docker/mysql/crawler

services:
  meta_ads_crawler:
    build:
      context: ./meta_ads_crawler
      dockerfile: Dockerfile
    image: meta_ads_crawler:latest
    container_name: meta_ads_crawler
    restart: always
    ports:
      - "8147:8147"
    secrets:
      - mysql_crawler
    environment:
      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler
      MYSQL_DB: crawler_dev
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler

      META_APP_ID: 822555046472581
      META_APP_SECRET: 1d63cc46243d28b50b0da5a6e2eefbcc
      META_GRAPH_API_URL: https://graph.facebook.com/v22.0
      META_REDIRECT_URI: https://api-dev.vadata.vn/ingest/partner/facebook/ad/callback

      CONNECTOR_CALLBACK_URL: https://qa.vadata.vn/callback.html
      CRAWLER_SERVICE_URL: http://vada-demo0:9206
