global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090
  - job_name: cloudprober
    static_configs:
    - targets:
      - mon.internal.vadata.vn:9313
  - job_name: node
    static_configs:
    - targets:
      - web.internal.vadata.vn:9100 
      - demo.internal.vadata.vn:9100 
      - prod.internal.vadata.vn:9100 
      - mon.internal.vadata.vn:9100
      - setup.internal.vadata.vn:9100
      - proxy01.internal.vadata.vn:9100 
      - proxy02.internal.vadata.vn:9100
      - backend00.internal.vadata.vn:9100
      - backend01.internal.vadata.vn:9100
      - mysql00.internal.vadata.vn:9100
      - bus00.internal.vadata.vn:9100
      - es00.internal.vadata.vn:9100
      - es01.internal.vadata.vn:9100
      - es02.internal.vadata.vn:9100
  - job_name: nginx
    static_configs:
    - targets:
      - proxy01.internal.vadata.vn:9113
      - proxy02.internal.vadata.vn:9113
  - job_name: nginx-vts
    static_configs:
    - targets:
      - proxy01.internal.vadata.vn
      - proxy02.internal.vadata.vn
    metrics_path: /status/format/prometheus
  - job_name: mysql
    static_configs:
    - targets:
      - mysql00.internal.vadata.vn:9104
  - job_name: kafka
    static_configs:
    - targets:
      - bus00.internal.vadata.vn:9308
      - bus01.internal.vadata.vn:9308
      - bus02.internal.vadata.vn:9308
  - job_name: elasticsearch
    static_configs:
    - targets:
      - mon.internal.vadata.vn:9114
      - mon.internal.vadata.vn:9115
      - es00.internal.vadata.vn:9114
      - es01.internal.vadata.vn:9114
      - es02.internal.vadata.vn:9114
  - job_name: blackbox_exporter  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['mon.internal.vadata.vn:9115']
  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        # DEV
        - https://qa.vadata.vn
        - https://dev-crm-api.vadata.vn/ping
        - https://ingestor.vadata.vn/health
        - https://acl.vadata.vn/health
        - https://dev-qe.vadata.vn/health
        - http://insert-dev.internal.vadata.vn/health
        - http://process-dev.internal.vadata.vn/health
        # VTAD
        - https://vtad.vn
        - https://api-vtad.vadata.vn/crm/ping
        - https://api-vtad.vadata.vn/ingest/health
        - https://api-vtad.vadata.vn/acl/health
        - http://qe-vtad.internal.vadata.vn/health
        - http://insert-vtad.internal.vadata.vn/health
        - http://process-vtad.internal.vadata.vn/health
        # PROD
        - https://app.vadata.vn
        - https://api-app.vadata.vn/crm/ping
        - https://api-app.vadata.vn/ingest/health
        - https://api-app.vadata.vn/acl/health
        - http://qe-app.internal.vadata.vn/health
        - http://insert-app.internal.vadata.vn/health
        - http://process-app.internal.vadata.vn/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mon.internal.vadata.vn:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - web.internal.vadata.vn 
        - demo.internal.vadata.vn
        - prod.internal.vadata.vn
        - mon.internal.vadata.vn
        - setup.internal.vadata.vn
        - proxy01.internal.vadata.vn
        - proxy02.internal.vadata.vn
        - backend00.internal.vadata.vn
        - backend01.internal.vadata.vn
        - mysql00.internal.vadata.vn
        - bus00.internal.vadata.vn
        - es00.internal.vadata.vn
        - es01.internal.vadata.vn
        - es02.internal.vadata.vn