global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090
  - job_name: cloudprober
    static_configs:
    - targets:
      - mon.internal.vadata.vn:9313
  - job_name: node
    static_configs:
    - targets:
      - web.internal.vadata.vn:9100 
      - demo.internal.vadata.vn:9100 
      - prod.internal.vadata.vn:9100 
      - mon.internal.vadata.vn:9100
      - setup.internal.vadata.vn:9100
      - proxy01.internal.vadata.vn:9100 
      - proxy02.internal.vadata.vn:9100
      - backend00.internal.vadata.vn:9100
      - backend01.internal.vadata.vn:9100
      - db00.internal.vadata.vn:9100
      - db01.internal.vadata.vn:9100
      - db02.internal.vadata.vn:9100
      - bus00.internal.vadata.vn:9100
      - bus01.internal.vadata.vn:9100
      - bus02.internal.vadata.vn:9100
  - job_name: nginx
    static_configs:
    - targets:
      - proxy01.internal.vadata.vn:9113
      - proxy02.internal.vadata.vn:9113
  - job_name: nginx-vts
    static_configs:
    - targets:
      - proxy01.internal.vadata.vn
      - proxy02.internal.vadata.vn
    metrics_path: /status/format/prometheus
  - job_name: mysql
    static_configs:
    - targets:
      - mysql00.internal.vadata.vn:9104
  - job_name: kafka
    static_configs:
    - targets:
      - bus00.internal.vadata.vn:9308
      - bus01.internal.vadata.vn:9308
      - bus02.internal.vadata.vn:9308
