networks:
  ihn-network:
    driver: bridge

services:
  ihn_change_receiver:
    build:
      context: .
      dockerfile: Dockerfile
    image: ihn_change_receiver:latest
    container_name: ihn_change_receiver
    restart: always
    volumes:
      - /var/lib/ihn/changes:/app/data
    environment:
      PORT: "8050"
    ports:
      - "8050:8050"
    networks:
      - ihn-network