services:
  kibana_vtad:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana_vtad
    env_file:
      - /var/secret/docker/es/vtad.env
    environment:
      - ELASTICSEARCH_HOSTS=http://setup.vadata.vn:9092
    ports:
      - "5601:5601"