secrets:
  tiktok_shop_app_secret:
    file: /var/secret/docker/tiktok/shop/app_secret
  mysql_crawler_prod:
    file: /var/secret/docker/mysql/crawler_prod

services:
  tiktok_ads_crawler:
    build:
      context: ./tiktok_ads_crawler
      dockerfile: Dockerfile
    image: tiktok_ads_crawler:latest
    container_name: tiktok_ads_crawler
    restart: always
    ports:
      - "8145:8145"
    secrets:
      - mysql_crawler_prod
    environment:
      LOG_LEVEL: 10

      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler_prod
      MYSQL_DB: crawler_prod
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler_prod

      TIKTOK_BIZ_API_URL: https://business-api.tiktok.com/open_api/v1.3
      TIKTOK_BIZ_APP_ID: 7480814660439146497
      TIKTOK_BIZ_SECRET: 6fd63e3c5a39cffd0dd2d73c872840008b587148
      TIKTOK_BIZ_REDIRECT_URI: https://api-app.vadata.vn/ingest/partner/tiktok/ad/callback

      INSERT_SERVICE_URL: http://insert-app.internal.vadata.vn
      CONNECTOR_CALLBACK_URL: https://app.vadata.vn/callback.html

  tiktok_shop_crawler:
    build:
      context: ./tiktok_shop_crawler
      dockerfile: Dockerfile
    image: tiktok_shop_crawler:latest
    container_name: tiktok_shop_crawler
    restart: always
    ports:
      - "8148:8148"
    secrets:
      - mysql_crawler_prod
      - tiktok_shop_app_secret
    environment:
      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler_prod
      MYSQL_DB: crawler_prod
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler_prod

      INSERT_SERVICE_BASEURL: http://insert-app.internal.vadata.vn

      TIKTOK_SHOP_APP_KEY: 6c6qtr3533gu3
      TIKTOK_SHOP_APP_SECRET_FILE: /run/secrets/tiktok_shop_app_secret
      TIKTOK_SHOP_AUTH_BASEURL: https://auth.tiktok-shops.com
      TIKTOK_SHOP_AUTH_LINK: https://services.tiktokshop.com/open/authorize?service_id=7358037259238688517
      TIKTOK_SHOP_AUTH_CALLBACK: https://app.vadata.vn/callback.html
      TIKTOK_SHOP_API_BASEURL: https://open-api.tiktokglobalshop.com