secrets:
  mysql_crawler:
    file: /var/secret/docker/mysql/crawler

services:
  tiktok_ads_crawler:
    build:
      context: ./tiktok_ads_crawler
      dockerfile: Dockerfile
    image: tiktok_ads_crawler:latest
    container_name: tiktok_ads_crawler
    restart: always
    ports:
      - "8145:8145"
    secrets:
      - mysql_crawler
    environment:
      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler
      MYSQL_DB: crawler_dev
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler
      TIKTOK_BIZ_API_URL: https://business-api.tiktok.com/open_api/v1.3
      TIKTOK_BIZ_APP_ID: 7480814660439146497
      TIKTOK_BIZ_SECRET: 6fd63e3c5a39cffd0dd2d73c872840008b587148
      INSERT_SERVICE_URL: http://insert-dev.internal.vadata.vn
      FACEBOOK_APP_ID: 822555046472581
      FACEBOOK_APP_SECRET: 1d63cc46243d28b50b0da5a6e2eefbcc
      FACEBOOK_ACCESS_TOKEN: EAALsHAVaa4UBO7zNjAaqAZBTZA502eiVEaBoRBmgcakyFM2m7rxmjx5xy8omP4htEYVde3pFDZBZCpBXQBuqwJrcZBaDCyIL13LrrcpM8LH5eT2GR4D2xqdvZBvMyZBnEael6OCHUnjSZBrwrlwmnIbqfNJ6vgpvAphTr9tXyn5YwvGBkELmtBtmHcH3Fcblh3ce9i1oNGqi