secrets:
  es:
    file: /var/secret/docker/es/elastic.passwd
  crm:
    file: /var/secret/docker/crm/user7500.passwd

services:  
  mappings:
    build:
      context: ../
      dockerfile: mappings/Dockerfile
    image: mappings:latest
    container_name: mappings
    environment:
      PORT: "8070"
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://es-dev.internal.vadata.vn:9200
      CRM_BASEURL: https://dev-crm-api.vadata.vn
      CRM_PASSWD_FILE: /run/secrets/crm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/health"]
    secrets:
      - es
      - crm
    ports:
      - "8070:8070"

