secrets:
  mysql_crawler:
    file: /var/secret/docker/mysql/crawler

services:
  shopee_crawler:
    build:
      context: ./shopee_crawler
      dockerfile: Dockerfile
    image: shopee_crawler:latest
    container_name: shopee_crawler
    restart: always
    ports:
      - "8150:8150"
    environment:
      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler
      MYSQL_DB: crawler_dev
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler

      INSERT_SERVICE_BASEURL: http://insert-dev.internal.vadata.vn

      SHOPEE_AUTH_BASEURL: https://partner.test-stable.shopeemobile.com
      SHOPEE_AUTH_LINK: https://partner.test-stable.shopeemobile.com/api/v2/shop/auth_partner
      SHOPEE_SHOP_AUTH_CALLBACK: https://qa.vadata.vn/callback.html
      SHOPEE_OPEN_API_BASEURL:  https://partner.test-stable.shopeemobile.com

      SHOPEE_PARTNER_ID: 1280774
      SHOPEE_PARTNER_KEY: 45666152706a714755716b46494a64656e534f5a46485961547146595953544e