secrets:
  mysql_crawler:
    file: /var/secret/docker/mysql/crawler
  shopee_partner_key:
    file: /var/secret/docker/shopee/partner_key

services:
  shopee_crawler:
    build:
      context: ./shopee_crawler
      dockerfile: Dockerfile
    image: shopee_crawler:latest
    container_name: shopee_crawler
    restart: always
    ports:
      - "8150:8150"
    secrets:
      - mysql_crawler
      - shopee_partner_key
    environment:
      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler
      MYSQL_DB: crawler_dev
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler

      INSERT_SERVICE_BASEURL: http://insert-dev.internal.vadata.vn

      SHOPEE_SHOP_AUTH_CALLBACK: https://qa.vadata.vn/callback.html
      API_BASE_URL:  https://api-dev.vadata.vn

      # Shopee Domain Configuration
      SHOPEE_PRODUCTION_API_DOMAIN: partner.shopeemobile.com
      SHOPEE_SANDBOX_API_DOMAIN: openplatform.sandbox.test-stable.shopee.sg
      SHOPEE_PRODUCTION_AUTH_DOMAIN: partner.shopeemobile.com
      SHOPEE_SANDBOX_AUTH_DOMAIN: open.sandbox.test-stable.s`hopee.com

  SHOPEE_PARTNER_ID: 1179887
  SHOPEE_PARTNER_KEY_FILE: /run/secrets/shopee_partner_key
