services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
    volumes:
      - /mnt/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    secrets:
      - db_root
    user: "100000:100000"
    ports:
      - "3306:3306"
    command:
      - --server-id=3
      - --report-host=db02.internal.vadata.vn
    networks:
      - mysql-network

  mysqlrouter:
    image: container-registry.oracle.com/mysql/community-router
    container_name: mysqlrouter
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_CREATE_ROUTER_USER: 0
    secrets:
      - db_root
    depends_on:
      - mysql
    ports:
      - "6446:6446"
      - "6447:6447"
    command: >
      sh -c "export MYSQL_PASSWORD=$(cat /run/secrets/db_root) && /run.sh mysqlrouter"
    networks:
      - mysql-network

  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter
    restart: unless-stopped
    volumes:
      - /var/secret/docker/exporter.cnf:/exporter/exporter.cnf
    command:
      - --mysqld.username=exporter
      - --mysqld.address=mysql:3306
      - --config.my-cnf=/exporter/exporter.cnf
    secrets:
      - db_exporter
    depends_on:
      - mysql
    ports:
      - "9104:9104"
    networks:
      - mysql-network

secrets:
  db_root:
    file: /var/secret/docker/db_root
  db_exporter:
    file: /var/secret/docker/db_exporter

networks:
  mysql-network:
    driver: bridge