services:
  mysql:
    image: mysql
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
    volumes:
      - /mnt/mysql:/var/lib/mysql
    secrets:
      - db_root
    user: "100000:100000"
    ports:
      - "3306:3306"
    networks:
      - mysql-network

secrets:
  db_root:
    file: db_root

networks:
  mysql-network:
    driver: bridge
