services:
  db:
    image: mysql
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
    volumes:
      - /mnt/mysql:/var/lib/mysql
    secrets:
      - db_root
    user: "100000:100000"
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter
    restart: unless-stopped
    command:
     - "--mysqld.username=exporter:$(cat /run/secrets/db_exporter)"
     - "--mysqld.address=mysql:3306"
    secrets:
      - db_exporter
    ports:
      - "9104:9104"
    networks:
      - mysql-network

secrets:
  db_root:
    file: db_root
  db_exporter:
    file: db_exporter

networks:
  mysql-network:
    driver: bridge
