secrets:
  es_elastic_vtad:
    file: /var/secret/docker/es/elastic_vtad
  crm_vtad:
    file: /var/secret/docker/crm/vtad_demo

networks:
  etl-vtad-network:
    driver: bridge

services:
  es_inserter_vtad:
    build:
      context: .
      dockerfile: Dockerfile.es_inserter
    image: es-inserter:latest
    container_name: es_inserter_vtad
    restart: always
    environment:
      PORT: "7000"
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic_vtad
      ELASTIC_USER: elastic
      ELASTIC_URL: http://setup.internal.vadata.vn:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
    secrets:
      - es_elastic_vtad
    ports:
      - "${PORT}:${PORT}"
    networks:
      - etl-vtad-network
  
  ingestor_vtad:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    image: ingestor:latest
    container_name: ingestor_vtad
    restart: always
    environment:
      PORT: "7001"
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      KAFKA_TOPIC: vtad_ingest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
    ports:
      - "${PORT}:${PORT}"
    networks:
      - etl-vtad-network
  
  kafka_to_es_vtad:
    build:
      context: .
      dockerfile: Dockerfile.kafka_to_es
    image: kafka-to-es:latest
    container_name: kafka_to_es_vtad
    restart: always
    environment:
      PORT: "7002"
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic_vtad
      ELASTIC_USER: elastic
      ELASTIC_URL: http://setup.internal.vadata.vn:9092
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      KAFKA_TOPIC: vtad_ingest
      CRM_BASEURL: "https://api.vtad.vn"
      CRM_PASSWD_FILE: /run/secrets/crm_vtad
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
    secrets:
      - es_elastic_vtad
      - crm_vtad
    ports:
      - "${PORT}:${PORT}"
    networks:
      - etl-vtad-network

