secrets:
  es_elastic_vtad:
    file: /var/secret/docker/es/elastic_vtad
  mongo_vtad:
    file: /var/secret/docker/mongo/vada

networks:
  etl-vtad-network:
    driver: bridge

services:
  es_inserter_vtad:
    build:
      context: .
      dockerfile: Dockerfile.es_inserter
    image: es-inserter:latest
    container_name: es_inserter_vtad
    restart: always
    environment:
      PORT: "7000"
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic_vtad
      ELASTIC_USER: elastic
      ELASTIC_URL: http://setup.internal.vadata.vn:9092
    secrets:
      - es_elastic_vtad
    ports:
      - "7000:7000"
    networks:
      - etl-vtad-network
  
  ingestor_vtad:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    image: ingestor:latest
    container_name: ingestor_vtad
    restart: always
    environment:
      PORT: "7001"
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      KAFKA_TOPIC: vtad_input
    ports:
      - "7001:7001"
    networks:
      - etl-vtad-network
  
  kafka_to_es_vtad:
    build:
      context: .
      dockerfile: Dockerfile.kafka_to_es
    image: kafka-to-es:latest
    container_name: kafka_to_es_vtad
    restart: always
    environment:
      PORT: "7002"
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic_vtad
      ELASTIC_USER: elastic
      ELASTIC_URL: http://jump-vtad.internal.vadata.vn:9092
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      KAFKA_TOPIC: vtad_input
      MONGO_URI_FILE: /run/secrets/mongo_vtad
    secrets:
      - es_elastic_vtad
      - mongo_vtad
    ports:
      - "7002:7002"
    networks:
      - etl-vtad-network

