secrets:
  es:
    file: /var/secret/docker/es/elastic.passwd
  jwt: 
    file: /var/secret/docker/ingest/jwt

services:
  insert:
    build:
      context: ../
      dockerfile: etl/Dockerfile.insert
    image: insert:latest
    container_name: insert
    restart: always
    environment:
      PORT: "8000"
      APP_ENV: app
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://es-app.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    secrets:
      - es
    ports:
      - "8000:8000"

  ingest:
    build:
      context: ../
      dockerfile: etl/Dockerfile.ingest
    image: ingest:latest
    container_name: ingest
    restart: always
    environment:
      PORT: "8001"
      APP_ENV: app
      MAPPINGS_BASEURL: http://mappings-app.internal.vadata.vn
      INSERT_BASEURL: http://insert-app.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
    secrets:
      - es
      - jwt
    ports:
      - "8001:8001"