secrets:
  es_elastic:
    file: /var/secret/docker/es/elastic
  crm_user7500:
    file: /var/secret/docker/crm/user7500

networks:
  etl-network:
    driver: bridge

services:
  es_inserter:
    build:
      context: .
      dockerfile: Dockerfile.es_inserter
    image: es-inserter:latest
    container_name: es_inserter
    restart: always
    environment:
      PORT: "8000"
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic
      ELASTIC_USER: elastic
      ELASTIC_URL: http://demo.internal.vadata.vn:9200
    secrets:
      - es_elastic
    ports:
      - "8000:8000"
    networks:
      - etl-network

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    image: ingestor:latest
    container_name: ingestor
    restart: always
    environment:
      PORT: "8001"
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      KAFKA_TOPIC: dev_input
    ports:
      - "8001:8001"
    networks:
      - etl-network
  
  kafka_to_es:
    build:
      context: .
      dockerfile: Dockerfile.kafka_to_es
    image: kafka-to-es:latest
    container_name: kafka_to_es
    restart: always
    environment:
      PORT: "8002"
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic
      ELASTIC_USER: elastic
      ELASTIC_URL: http://demo.internal.vadata.vn:9200
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      KAFKA_TOPIC: dev_input
      CRM_BASEURL: "https://dev-crm-api.vadata.vn"
      CRM_PASSWD_FILE: /run/secrets/crm_user7500
    secrets:
      - es_elastic
      - crm
    ports:
      - "8002:8002"
    networks:
      - etl-network

