secrets:
  es:
    file: /var/secret/docker/es/elastic.passwd
  jwt:
    file: /var/secret/docker/ingest/jwt

services:
  log:
    build:
      context: ../
      dockerfile: etl/Dockerfile.log
    image: log:latest
    container_name: log
    restart: always
    environment:
      PORT: "8003"
      APP_ENV: dev
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://demo.internal.vadata.vn:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
    secrets:
      - es
    ports:
      - "8003:8003"

  insert:
    build:
      context: ../
      dockerfile: etl/Dockerfile.insert
    image: insert:latest
    container_name: insert
    restart: always
    environment:
      PORT: "8000"
      APP_ENV: dev
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://demo.internal.vadata.vn:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    secrets:
      - es
    ports:
      - "8000:8000"

  ingest:
    build:
      context: ../
      dockerfile: etl/Dockerfile.ingest
    image: ingest:latest
    container_name: ingest
    restart: always
    environment:
      PORT: "8001"
      APP_ENV: dev
      INSERT_BASEURL: http://insert-dev.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
    secrets:
      - es
      - jwt
    ports:
      - "8001:8001"
