secrets:
  es:
    file: /var/secret/docker/es/elastic.passwd

services:
  es_inserter:
    build:
      context: ../
      dockerfile: etl/Dockerfile.es_inserter
    image: es_inserter:latest
    container_name: es_inserter
    restart: always
    environment:
      PORT: "8000"
      APP_ENV: prod
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://es-app.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    secrets:
      - es
    ports:
      - "8000:8000"

  ingestor:
    build:
      context: ../
      dockerfile: etl/Dockerfile.ingestor
    image: ingestor:latest
    container_name: ingestor
    restart: always
    environment:
      PORT: "8001"
      APP_ENV: prod
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://es-app.internal.vadata.vn
      MAPPINGS_BASEURL: http://mappings-app.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
    secrets:
      - es
    ports:
      - "8001:8001"
  
  kafka_to_es:
    build:
      context: ../
      dockerfile: etl/Dockerfile.kafka_to_es
    image: kafka_to_es:latest
    container_name: kafka_to_es
    restart: always
    environment:
      PORT: "8002"
      APP_ENV: prod
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://es-app.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
    secrets:
      - es
    ports:
      - "8002:8002"

