secrets:
  es:
    file: /var/secret/docker/es/elastic.passwd

services:
  insert:
    build:
      context: ../
      dockerfile: etl/Dockerfile.insert
    image: insert:latest
    container_name: insert
    restart: always
    environment:
      PORT: "8000"
      APP_ENV: dev
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://demo.internal.vadata.vn:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    secrets:
      - es
    ports:
      - "8000:8000"

  ingest:
    build:
      context: ../
      dockerfile: etl/Dockerfile.ingest
    image: ingest:latest
    container_name: ingest
    restart: always
    environment:
      PORT: "8001"
      APP_ENV: dev
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://demo.internal.vadata.vn:9200
      MAPPINGS_BASEURL: http://mappings-dev.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
    secrets:
      - es
    ports:
      - "8001:8001"
  
  process:
    build:
      context: ../
      dockerfile: etl/Dockerfile.process
    image: process:latest
    container_name: process
    restart: always
    environment:
      PORT: "8002"
      APP_ENV: dev
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://demo.internal.vadata.vn:9200
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
    secrets:
      - es
    ports:
      - "8002:8002"

