secrets:
  es:
    file: /var/secret/docker/es/elastic.passwd

services:
  es_inserter:
    build:
      context: ../
      dockerfile: etl/Dockerfile.es_inserter
    image: es_inserter:latest
    container_name: es_inserter
    restart: always
    environment:
      PORT: "7000"
      APP_ENV: vtad
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://es-vtad.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
    secrets:
      - es
    ports:
      - "7000:7000"
  
  ingestor:
    build:
      context: ..
      dockerfile: etl/Dockerfile.ingestor
    image: ingestor:latest
    container_name: ingestor
    restart: always
    environment:
      PORT: "7001"
      APP_ENV: vtad
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://demo.internal.vadata.vn:9200
      MAPPINGS_BASEURL: http://mappings.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/health"]
    secrets:
      - es
    ports:
      - "7001:7001"
  
  kafka_to_es:
    build:
      context: ..
      dockerfile: etl/Dockerfile.kafka_to_es
    image: kafka_to_es:latest
    container_name: kafka_to_es
    restart: always
    environment:
      PORT: "7002"
      APP_ENV: vtad
      ELASTIC_PASSWD_FILE: /run/secrets/es
      ELASTIC_USER: elastic
      ELASTIC_URL: http://es-vtad.internal.vadata.vn
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002/health"]
    secrets:
      - es
    ports:
      - "7002:7002"