secrets:
  es_elastic_vtad:
    file: /var/secret/docker/es/elastic_vtad
  crm_vtad:
    file: /var/secret/docker/crm/vtad

networks:
  etl_vtad_network:
    driver: bridge

services:
  es_inserter_vtad:
    build:
      context: .
      dockerfile: Dockerfile.es_inserter
    image: es_inserter:latest
    container_name: es_inserter_vtad
    restart: always
    environment:
      PORT: "7000"
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic_vtad
      ELASTIC_USER: elastic
      ELASTIC_URL: http://setup.internal.vadata.vn:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
    secrets:
      - es_elastic_vtad
    ports:
      - "7000:7000"
    networks:
      - etl_vtad_network
  
  ingestor_vtad:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    image: ingestor:latest
    container_name: ingestor_vtad
    restart: always
    environment:
      PORT: "7001"
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      KAFKA_TOPIC: vtad_ingest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/health"]
    ports:
      - "7001:7001"
    networks:
      - etl_vtad_network
  
  kafka_to_es_vtad:
    build:
      context: .
      dockerfile: Dockerfile.kafka_to_es
    image: kafka_to_es:latest
    container_name: kafka_to_es_vtad
    restart: always
    environment:
      PORT: "7002"
      ELASTIC_PASSWD_FILE: /run/secrets/es_elastic_vtad
      ELASTIC_USER: elastic
      ELASTIC_URL: http://setup.internal.vadata.vn:9092
      KAFKA_BROKER_URL: kafka.ilb.vadata.vn:9092
      KAFKA_TOPIC: vtad_ingest
      MAPPING_BASEURL: http://mappings-vtad.internal.vadata.vn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002/health"]
    secrets:
      - es_elastic_vtad
      - crm_vtad
    ports:
      - "7002:7002"
    networks:
      - etl_vtad_network

