FROM python
WORKDIR /app

ENV TZ=Asia/Ho_Chi_Minh
RUN apt-get update && apt-get install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apt-get clean

COPY etl/requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt
COPY .. /app
CMD uvicorn etl.insert.main:app --host 0.0.0.0 --port $PORT --workers 1
