FROM python
WORKDIR /app
COPY etl/requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt
COPY .. /app
CMD uvicorn etl.es_inserter.kafka_to_es:app --host 0.0.0.0 --port $PORT --workers 6