networks:
  nginx-network:
    driver: bridge

services:
  nginx:
    image: nginx-vts:1.24
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - kafka-ui
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/ssl/letsencrypt:/etc/nginx/ssl
    networks:
      - nginx-network
  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - "--nginx.scrape-uri=http://nginx/stub"
    networks:
      - nginx-network

secrets:
  kafka-ui:
    file: /var/secret/nginx/kafka.access
