routes:
  - name: "crm-api"
    auth:
      url: "https://dev-crm-api.vadata.vn/auth/login"
      type: "login"
      payload:
        username: "user7500"
        password: "mypassword"
      token_field: "access_token"   # the JSON field containing the token
    apis:
      - url: "https://dev-crm-api.vadata.vn/querybuilder/master_file/operator_all"
        method: "GET"
        expected_schema:
          type: object
          properties:
            operators: {type: object}
          required: ["operators"]
    
      - url: "https://dev-crm-api.vadata.vn/v1/workspaces?limit=1000"
        method: "GET"
        expected_schema:
          type: object
          properties:
            data: {type: array}
            pagination: {type: object}
          required: ["data", "pagination"]

      - url: "https://dev-crm-api.vadata.vn/v1/directory_tree"
        method: "GET"
        expected_schema:
          type: object
          properties:
            tree: {type: array}
          required: ["tree"]

      - url: "https://dev-crm-api.vadata.vn/v1/querybuilder/master_file/index"
        method: "GET"
        expected_schema:
          type: object
          properties:
            indices: {type: array}
          required: ["indices"]

      - url: "https://acl.vadata.vn/v1/settings/workspace/68120cf482815478186c86f8/user/65422b6aa2bbacc10b7a22a3"
        method: "GET"
        expected_schema:
          type: object
          properties:
            data: {type: object}
          required: ["data"]

      - url: "https://dev-crm-api.vadata.vn/v1/querybuilder/master_file/treebeard/demo_distribute_data"
        method: "GET"
        expected_schema:
          type: object
          properties:
            index: {type: object}
          required: ["index"]

      - url: "https://dev-crm-api.vadata.vn/v1/querybuilder/master_file/attribute/demo_distribute_data"
        method: "GET"
        expected_schema:
          type: object
          properties:
            attributes: {type: array}
          required: ["attributes"]