global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090
  - job_name: node
    static_configs:
    - targets:
      - web.internal.vadata.vn:9100 
      - demo.internal.vadata.vn:9100 
      - prod.internal.vadata.vn:9100 
      - mon.internal.vadata.vn:9100
      - setup.internal.vadata.vn:9100
      - proxy01.internal.vadata.vn:9100 
      - proxy02.internal.vadata.vn:9100 