secrets:
  google_app_secret:
    file: /var/secret/docker/google/app_secret
  mysql_crawler_prod:
    file: /var/secret/docker/mysql/crawler_prod

services:
  google_ads_crawler:
    build:
      context: ./google_ads_crawler
      dockerfile: Dockerfile
    image: google_ads_crawler:latest
    container_name: google_ads_crawler
    restart: always
    ports:
      - "8146:8146"
    environment:
      API_BASE_URL: https://api-app.vadata.vn
      GOOGLE_APP_SECRET_FILE: /run/secrets/google_app_secret
      GOOGLE_DEVELOPER_TOKEN: "3WREvqoZUexzpH_oDUjOPw"
      INSERT_SERVICE_BASEURL: http://insert-app.internal.vadata.vn
      CALLBACK_FINAL_URL: https://app.vadata.vn/callback.html
      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler_prod
      MYSQL_DB: crawler_prod
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler_prod
    secrets:
      - google_app_secret
      - mysql_crawler_prod
