secrets:
  google_app_secret:
    file: /var/secret/docker/google/app_secret

services:
  google_ads_crawler:
    build:
      context: ./google_ads_crawler
      dockerfile: Dockerfile
    image: google_ads_crawler:latest
    container_name: google_ads_crawler
    restart: always
    ports:
      - "8146:8146"
    environment:
      GOOGLE_APP_SECRET_FILE: /run/secrets/google_app_secret
    secrets:
      - google_app_secret
