secrets:
  mysql_crawler:
    file: /var/secret/docker/mysql/crawler
  nhanh_secret_key:
    file: /var/secret/docker/nhanh/secret_key

services:
  nhanh_crawler:
    build:
      context: ./nhanh_crawler
      dockerfile: Dockerfile
    image: nhanh_crawler:latest
    container_name: nhanh_crawler
    restart: always
    ports:
      - "8149:8149"
    secrets:
      - mysql_crawler
      - nhanh_secret_key
    environment:
      APP_ENV: dev

      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler
      MYSQL_DB: crawler_dev
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler

      NHANH_APP_ID: 75154
      NHANH_BASE_URL: https://pos.open.nhanh.vn/api
      NHANH_RETURN_LINK: https://api-dev.vadata.vn/ingest/partner/nhanh/platform/callback
      NHANH_SECRET_KEY_FILE: /run/secrets/nhanh_secret_key

      INSERT_SERVICE_BASEURL: http://insert-dev.internal.vadata.vn
      CONNECTOR_CALLBACK_URL: https://qa.vadata.vn/callback.html
