secrets:
  mysql_crawler_prod:
    file: /var/secret/docker/mysql/crawler_prod
  nhanh_secret_key:
    file: /var/secret/docker/nhanh/secret_key

services:
  nhanh_crawler:
    build:
      context: ./nhanh_crawler
      dockerfile: Dockerfile
    image: nhanh_crawler:latest
    container_name: nhanh_crawler
    restart: always
    ports:
      - "8149:8149"
    secrets:
      - mysql_crawler_prod
      - nhanh_secret_key
    environment:
      MYSQL_HOST: mysql00.internal.vadata.vn
      MYSQL_USER: crawler_prod
      MYSQL_DB: crawler_prod
      MYSQL_PASSWD_FILE: /run/secrets/mysql_crawler_prod

      NHANH_APP_ID: 75154
      NHANH_BASE_URL: https://pos.open.nhanh.vn/api
      NHANH_RETURN_LINK: https://api-app.vadata.vn/ingest/partner/nhanh/platform/callback
      NHANH_SECRET_KEY_FILE: /run/secrets/nhanh_secret_key

      INSERT_SERVICE_BASEURL: http://insert-app.internal.vadata.vn
      CONNECTOR_CALLBACK_URL: https://client.vadata.vn/callback.html
