services:
  broker:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    network_mode: host
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://bus01.internal.vadata.vn:9092,CONTROLLER://bus01.internal.vadata.vn:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://bus01.internal.vadata.vn:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@bus00.internal.vadata.vn:9093,2@bus01.internal.vadata.vn:9093,3@bus02.internal.vadata.vn:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    volumes:
      - /var/secret/docker/kafka:/etc/secret
      - /mnt/bus/kafka:/tmp/kafka-logs
