services:
  broker:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    network_mode: host
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: SASL_PLAINTEXT://bus00.internal.vadata.vn:9092,CONTROLLER://bus00.internal.vadata.vn:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://bus00.internal.vadata.vn:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@bus00.internal.vadata.vn:9093,2@bus01.internal.vadata.vn:9093,3@bus02.internal.vadata.vn:9093
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT