services:
  es:
    build:
      context: .
      dockerfile: Dockerfile
    image: elasticsearch:8.10.4-vada
    container_name: es
    network_mode: "host"
    restart: always
    environment:
      - node.name=es03.internal.vadata.vn
      - cluster.name=qa
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/es/data:/usr/share/elasticsearch/data

  es_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: es_exporter
    network_mode: "host"
    command:
     - "--es.uri=http://localhost:9200"
    restart: always
    env_file:
      - /var/secret/docker/es/exporter.env