services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:24.2.3
    container_name: cloudbeaver
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    ports:
      - "8978:8978"

volumes:
  cloudbeaver_data:
