FROM python:3.11.11-alpine
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8145
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8145"]
