services:  
  frontend: &fe
    image: vada898989.azurecr.io/prod-webapp:prod-989ea906
    container_name: frontend
    ports:
      - "3000:80"

  frontend_vtad:
    <<: *fe
    image: vada898989.azurecr.io/mix-webapp:mix-989ea906
    container_name: frontend_vtad
    ports:
      - "3001:80"

  crm:
    image: vada898989.azurecr.io/crm-api:2f644aba
    container_name: crm
    ports:
      - "8080:8080"
    env_file:
      - /var/secret/docker/crm/app.env
    environment:
      - APP_ENV=development
      - SERVER_ADDRESS=:8080
      - CONTEXT_TIMEOUT=2
      - MONGODB_DATABASE_NAME=vada_prod
      - ACCESS_TOKEN_EXPIRY_HOUR=48
      - REFRESH_TOKEN_EXPIRY_HOUR=168
      - MAILGUN_DOMAIN=mg.vadata.vn
      - VADA_BACKEND_URL=http://qe-app.internal.vadata.vn/
      - VADA_FRONTEND_URL=https://app.vadata.vn/
      - VADA_ACL_URL=http://acl-app.internal.vadata.vn/
      - ENABLE_SERVICE_PACKAGE=false

  qe: &qe
    image: vada898989.azurecr.io/vada-query-engine:es-8.10.0
    container_name: qe
    pull_policy: always
    ports:
      - "9675:9675"
    env_file:
      - /var/secret/docker/qe/app.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9675/health"]
  qe_replica:
    <<: *qe
    container_name: qe_replica
    ports:
      - "9676:9675"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    ports:
      - "5601:5601"
    env_file:
      - /var/secret/docker/es/kibana.env
    environment:
      - ELASTICSEARCH_HOSTS=http://es-app.internal.vadata.vn
      - STATUS_ALLOWANONYMOUS=true
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s http://localhost:5601/api/status"]