secrets:
  google_app_secret:
    file: /var/secret/docker/google/app_secret

services:
  crawler-api:
    build:
      context: ./google_crawler
      dockerfile: Dockerfile
    image: google_crawler:latest
    container_name: google_crawler
    restart: always
    ports:
      - "8146:8146"
    environment:
      GOOGLE_APP_SECRET_FILE: /run/secrets/google_app_secret
    secrets:
      - google_app_secret
